name: counter_uav_marl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.8
  - numpy
  - gymnasium
  - pettingzoo
  - matplotlib
  - pyyaml
  - scipy
  - tensorboard
  - pytest
  - pip
